openapi: "3.0.0"
info:
    version: "1.0.0"
    title: honeydome-broker-web
    description: honeydome-broker web 访问的 openAPI 文档
servers:
    - url: localhost
      description: local server stub
paths:
    /kline:
        get:
            description: 查询K线历史数据
            operationId: getKlines
            parameters:
                - name: exchange
                  description: 交易所名称
                  example: HUOBI
                  in: query
                  required: true
                  schema:
                      type: string
                      enum:
                          - HUOBI
                          - OKEX
                          - BINANCE
                - name: symbol
                  description: 交易对名称
                  example: btc/usdt
                  in: query
                  required: true
                  schema:
                      type: string
                - name: period
                  description: 查询的K线的粒度
                  in: query
                  required: true
                  schema:
                      type: string
                      enum:
                          - MINUTE
                          - QUARTER
                          - HOUR
                          - DAY
                          - WEEK
                - name: start
                  description: 查询开始时间
                  in: query
                  schema:
                      type: string
                      format: 'date-time'
                - name: end
                  description: 查询结束时间
                  in: query
                  schema:
                      type: string
                      format: 'date-time'
                - name: page
                  description: 分页查询中，当前页数
                  in: query
                  required: true
                  schema:
                      type: integer
                - name: size
                  description: 分页查询中，当前也中K线数量
                  in: query
                  required: true
                  schema:
                      type: integer
            responses:
                200:
                    description: 返回指定查询范围内的K线数据
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/KlineListPage'
components:
    schemas:
        Page:
            description: 表数据的分页信息
            type: object
            properties:
                totalElements:
                    type: integer
                    default: 100
                totalPages:
                    type: integer
                    default: 10
                size:
                    type: integer
                    default: 10
        Kline:
            description: K线数据项
            type: object
            properties:
                open:
                    type: string
                    format: float
                close:
                    type: string
                    format: float
                high:
                    type: string
                    format: float
                low:
                    type: string
                    format: float
                vol:
                    type: string
                    format: float
                time:
                    type: string
                    format: 'date-time'
        KlineListPage:
            description: 分页的K线数据集
            type: object
            properties:
                data:
                    type: array
                    items:
                        $ref: '#/components/schemas/Kline'
                page:
                    $ref: '#/components/schemas/Page'
